class Sentences {
  static const List<String> sentencesEasyLevel = [
    "Birds fly in sky",
    "Dogs run very fast",
    "Cats sleep all day",
    "Kids play at school",
    "Sun shines every morning",
    "Fish swim in water",
    "Trees give nice shade",
    "Stars shine at night",
    "Mom cooks tasty soup",
    "Baby laughs at balloons",
    "Waves move to shore",
    "Wind moves the leaves",
    "Birds sing every morning",
    "Clouds float above us",
    "Frogs jump in ponds",
    "Rain falls on grass",
    "Kids read short books",
    "Dogs bark at strangers",
    "Birds build tiny nests",
    "Snow covers the ground",
  ];

  static const List<String> sentencesMediumLevel = [
    "Luis ate a bread yesterday afternoon",
    "Birds fly freely high in skies",
    "The ocean is filled with fish",
    "The rainbow has many pretty colors",
    "Elena is a very good student",
    "My dog runs quickly at home",
    "Cats sleep calmly on comfy sofas",
    "The sun shines brightly every morning",
    "Kids play happily in the playground",
    "The teacher reads stories to kids",
    "The moon softly lights the night",
    "My sister paints flowers in notebooks",
    "Fish always swim together in aquariums",
    "The cat chases balls around home",
    "The stars shine brightly all night",
    "My mom cooks soup for everyone",
    "The baby laughs loudly seeing balloons",
    "Trees give shade in the park",
    "Kids sing together at the school",
    "The train travels quickly through mountains",
  ];

  static const List<String> sentencesHardLevel = [
    "The friendly dog happily runs around our yard",
    "Kids read interesting books during class at school",
    "The bright sun shines warmly over the park",
    "My little sister draws colorful pictures at home",
    "The teacher tells funny stories to her students",
    "Birds build their tiny nests high in trees",
    "The happy baby laughs loudly when seeing balloons",
    "Our family walks together every evening near home",
    "The big train moves quickly across the mountains",
    "Cats quietly watch birds flying over the garden",
    "Ocean waves crash gently onto the sandy beach",
    "My brother plays soccer happily with his friends",
    "Stars sparkle brightly across the peaceful night sky",
    "The kids explore nature during their school trip",
    "Mom prepares delicious meals for us each day",
    "The friendly cat follows me around the house",
    "My cousin collects shiny rocks during our adventures",
    "The little bird sings beautifully in the morning",
    "Children practice drawing animals in their classrooms",
    "The family enjoys picnics together on sunny weekends",
  ];
}
