class BonusWords {
  static List bonusWords = [
    {
      "word": "ANIMALS",
      "options": [
        "BEE",
        "CAT",
        "DOG",
        "FISH",
        "HORSE",
        "LION",
        "MOUSE",
        "TIGER",
        "WOLF",
        "ZEBRA",
      ],
    },
    {
      "word": "COLORS",
      "options": [
        "RED",
        "GREEN",
        "BLUE",
        "YELLOW",
        "ORANGE",
        "PURPLE",
        "BROWN",
        "BLACK",
        "WHITE",
        "GRAY",
      ],
    },
    {
      "word": "COUNTRIES",
      "options": [
        "CANADA",
        "CHINA",
        "FRANCE",
        "GERMANY",
        "ITALY",
        "JAPAN",
        "MEXICO",
        "SPAIN",
        "UK",
        "USA",
      ],
    },

    {
      "word": "BODY PARTS",
      "options": [
        "HEAD",
        "HAND",
        "LEG",
        "ARM",
        "EYE",
        "EAR",
        "NOSE",
        "MOUTH",
        "FOOT",
        "HAIR",
      ],
    },
    {
      "word": "DAYS",
      "options": [
        "MONDAY",
        "TUESDAY",
        "WEDNESDAY",
        "THURSDAY",
        "FRIDAY",
        "SATURDAY",
        "SUNDAY",
      ],
    },
    {
      "word": "FRUITS",
      "options": [
        "APPLE",
        "BANANA",
        "ORANGE",
        "GRAPE",
        "PEAR",
        "PINEAPPLE",
        "WATERMELON",
        "STRAWBERRY",
        "KIWI",
        "MANGO",
      ],
    },
    {
      "word": "VEGETABLES",
      "options": [
        "CARROT",
        "POTATO",
        "TOMATO",
        "LETTUCE",
        "BROCCOLI",
        "CUCUMBER",
        "ONION",
        "PEPPER",
        "CORN",
        "SPINACH",
      ],
    },
    {
      "word": "SCHOOL OBJECTS",
      "options": [
        "PENCIL",
        "PEN",
        "ERASER",
        "MARKER",
        "NOTEBOOK",
        "BOOK",
        "RULER",
        "SCISSORS",
        "GLUE",
        "BACKPACK",
      ],
    },
    {
      "word": "SPORTS",
      "options": [
        "SOCCER",
        "BASKETBALL",
        "BASEBALL",
        "SWIMMING",
        "TENNIS",
        "VOLLEYBALL",
        "BOXING",
        "GOLF",
        "SKATEBOARDING",
        "CYCLING",
      ],
    },
    {
      "word": "TRANSPORT",
      "options": [
        "CAR",
        "BUS",
        "TRAIN",
        "PLANE",
        "BOAT",
        "BIKE",
        "MOTORCYCLE",
        "SUBWAY",
        "TAXI",
        "TRUCK",
      ],
    },
    {
      "word": "CLOTHES",
      "options": [
        "SHIRT",
        "PANTS",
        "JACKET",
        "DRESS",
        "HAT",
        "SHOES",
        "SOCKS",
        "SKIRT",
        "SWEATER",
        "SHORTS",
      ],
    },
    {
      "word": "WEATHER",
      "options": [
        "SUNNY",
        "RAINY",
        "CLOUDY",
        "WINDY",
        "STORMY",
        "SNOWY",
        "HOT",
        "COLD",
        "FOGGY",
        "WARM",
      ],
    },
    {
      "word": "FAMILY MEMBERS",
      "options": [
        "MOTHER",
        "FATHER",
        "BROTHER",
        "SISTER",
        "GRANDMA",
        "GRANDPA",
        "AUNT",
        "UNCLE",
        "COUSIN",
        "BABY",
      ],
    },
  ];
}
